enableTelemetry: false

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-node_auth_token}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
